<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YouTube_wpcf7-form-control wpcf7-submit</name>
   <tag></tag>
   <elementGuidId>304aa09b-a9a1-41ed-ac2b-29c627c204d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Send'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa4d317d-a293-4bc5-b3fc-27dcea49f38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>614c7b13-f7e0-47a0-b9dd-75b7e45e11ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>2bde94be-c2cb-45b7-b2b1-ab2947249277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-submit</value>
      <webElementGuid>76e26bb8-db23-4a9e-9ccb-a20d8cb5746d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f3607-o2&quot;)/form[@class=&quot;wpcf7-form mailchimp-ext-0.5.48 init&quot;]/p[3]/input[@class=&quot;wpcf7-form-control wpcf7-submit&quot;]</value>
      <webElementGuid>7e84b0c2-cd6e-4d91-abf1-f98e2b5fbc70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Send'])[2]</value>
      <webElementGuid>732fcd9e-4408-4ee9-8537-0cef8fce39ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f3607-o2']/form/p[3]/input</value>
      <webElementGuid>8532fcf3-728c-417e-9ef7-16cab329fee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>1d6b9bd9-b8a6-4005-b020-0857a1e404c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>65292bdd-3721-442f-8d9d-947ac4fa3265</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
