<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get Started_leadinModal-close</name>
   <tag></tag>
   <elementGuidId>42204674-ce2c-46a8-8c96-c17a8a490318</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leadinModal-1937919']/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.leadinModal-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>03d71cf1-aa4d-4a70-9243-4221fdd84fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leadinModal-close</value>
      <webElementGuid>0013f222-e6be-45a6-9e4e-38b9b7e9419e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>af287d6e-900f-4e73-bded-c2950f2179be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leadinModal-1937919&quot;)/div[@class=&quot;leadinModal-content&quot;]/button[@class=&quot;leadinModal-close&quot;]</value>
      <webElementGuid>7115a7bf-d691-4877-bca4-1c856a3d5c93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leadinModal-1937919']/div[2]/button</value>
      <webElementGuid>8e9b30ff-0383-478f-a894-1ac8f12aee98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e0f4394a-62f2-4b8e-a398-8415059bdc4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
