<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RAM per server (contoh 16 GB)_ram-server</name>
   <tag></tag>
   <elementGuidId>83940087-85d4-4c9c-a1ce-5ce513992cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ram-server']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ram-server&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d13a90c-9f87-4bda-915c-6799cbe0dafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8975b3fa-cb88-4fea-922a-93936f7a96c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ram-server</value>
      <webElementGuid>7820bd00-0d35-4e9f-949d-00ddcb9bb340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>c7739df5-88a7-46eb-8db7-8a452b1a821c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-text</value>
      <webElementGuid>e49a9d14-bbc0-4828-9eec-d3691fa1387c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>136f7874-4083-4991-9d24-5d902a2ead6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f8170-p5984-o1&quot;)/form[@class=&quot;wpcf7-form mailchimp-ext-0.5.48 init&quot;]/p[3]/label[3]/span[@class=&quot;wpcf7-form-control-wrap ram-server&quot;]/input[@class=&quot;wpcf7-form-control wpcf7-text&quot;]</value>
      <webElementGuid>17726be5-d0a6-43af-aebf-e638a791b921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ram-server']</value>
      <webElementGuid>ff294f19-b323-44c4-81c9-08634e0cfc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f8170-p5984-o1']/form/p[3]/label[3]/span/input</value>
      <webElementGuid>2d317a73-7dbb-49fc-9118-e1e67e45e5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/label[3]/span/input</value>
      <webElementGuid>1caae8ee-effd-4e9b-8599-18670089cabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ram-server']</value>
      <webElementGuid>354526d1-fd32-4795-8470-b95569dc6b64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
