<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Telepon Anda_your-phone</name>
   <tag></tag>
   <elementGuidId>b9af9bbf-6a07-4998-90e7-214eda9f784a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='your-phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;your-phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07da4cda-2c47-49ad-a053-6f85beff9c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>ce84951e-4719-46c6-884b-02ec5a8baa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>your-phone</value>
      <webElementGuid>6267082d-6e12-44a5-9fda-063f21797e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4e2e1b86-4ab5-4a43-b3ad-1f29c3c3c574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-text wpcf7-tel wpcf7-validates-as-required wpcf7-validates-as-tel</value>
      <webElementGuid>37fd78ea-33f9-4b24-abc6-ae556887d4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9651a4b5-aa0b-4595-8401-45cd2c055281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ad53036-6a3a-40d1-afaf-48bf8b6d1606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f8170-p5984-o1&quot;)/form[@class=&quot;wpcf7-form mailchimp-ext-0.5.48 init&quot;]/p[1]/label[4]/span[@class=&quot;wpcf7-form-control-wrap your-phone&quot;]/input[@class=&quot;wpcf7-form-control wpcf7-text wpcf7-tel wpcf7-validates-as-required wpcf7-validates-as-tel&quot;]</value>
      <webElementGuid>609971bc-ce37-49e1-b914-e381bcb2cd43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='your-phone']</value>
      <webElementGuid>5ec64023-711c-40d3-9780-28cb30583644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f8170-p5984-o1']/form/p/label[4]/span/input</value>
      <webElementGuid>071a39ca-4946-4714-a688-5c0739be46bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/span/input</value>
      <webElementGuid>5f39e841-e1fc-486c-8e85-b1dcb9ea4f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'your-phone']</value>
      <webElementGuid>00ac2e30-1781-4723-88a7-29ea5922535a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
