<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Session maksimum dalam suatu waktu pe_066f24</name>
   <tag></tag>
   <elementGuidId>d9946e10-81d9-4a4a-9729-7abcbdb7722e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='max-session']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;max-session&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dd53d17-2279-4b9e-b30c-0bf3a8ee9fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ac8f904-757e-4a55-bf86-3ebdc9bbf95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>max-session</value>
      <webElementGuid>156fb212-dd10-41b8-9b90-dfc0420ac02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>975894af-64d3-4039-9265-8f35493b7768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-text</value>
      <webElementGuid>8ce2743b-48cb-463a-85e2-d452d01efedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2c955f45-d4ad-435b-be11-8779118bc792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f8170-p5984-o1&quot;)/form[@class=&quot;wpcf7-form mailchimp-ext-0.5.48 init&quot;]/p[3]/label[1]/span[@class=&quot;wpcf7-form-control-wrap max-session&quot;]/input[@class=&quot;wpcf7-form-control wpcf7-text&quot;]</value>
      <webElementGuid>a03b4ad0-1663-4f36-8f4f-bab54b882856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='max-session']</value>
      <webElementGuid>10c8ac49-7b50-4b7d-a02f-f99b7a2c45da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f8170-p5984-o1']/form/p[3]/label/span/input</value>
      <webElementGuid>4fa64391-8e03-46a7-952d-fde6e86fb5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/label/span/input</value>
      <webElementGuid>291cde74-e69f-49e3-a4c5-bad369e700c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'max-session']</value>
      <webElementGuid>d488bf8f-5a05-4b0d-be64-02501e63153b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
