<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rata-rata konsumsi data per session (_dc38a1</name>
   <tag></tag>
   <elementGuidId>2d1e0584-8b47-4beb-9899-35ce4a40ef4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='avg-data']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;avg-data&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67ae3bc4-9aab-4b96-a2b0-523aff634ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e6ffd83-3042-4838-960a-a36e0738536b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>avg-data</value>
      <webElementGuid>0738d969-2570-49d3-b852-bc43e1d01db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>1e242de6-277b-4e0a-8f34-8d18c477df53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-text</value>
      <webElementGuid>a2652679-e423-4761-bba2-5c294770026c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d974a92-fe04-4338-ab33-14548b30bd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f8170-p5984-o1&quot;)/form[@class=&quot;wpcf7-form mailchimp-ext-0.5.48 init&quot;]/p[3]/label[2]/span[@class=&quot;wpcf7-form-control-wrap avg-data&quot;]/input[@class=&quot;wpcf7-form-control wpcf7-text&quot;]</value>
      <webElementGuid>7485b901-3b28-4c53-aaef-2a8978f3dd0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='avg-data']</value>
      <webElementGuid>0472085d-db1e-4f91-8aa4-3f41b0e8b7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f8170-p5984-o1']/form/p[3]/label[2]/span/input</value>
      <webElementGuid>0f19b6af-6b1e-4641-a65a-055cfd556568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/label[2]/span/input</value>
      <webElementGuid>b605b950-fe0c-4c49-bae3-e100ac9ffc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'avg-data']</value>
      <webElementGuid>40af974e-aba5-42c3-9c46-088ed5b5563a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
